### PR TITLE
Add new form, create game

### PR DESCRIPTION
**Pull request by jwmunn**
- Installed Simple Form 
- Created games#new form
- Create game on submit and redirect to game#show view
- Moved games#new form to a modal on games#index view

### CODE REVIEW

**Comment by jwmunn** [comment]
[Create Game#show view and draw chess board.](https://trello.com/c/XhAI50n1/12-create-game-show-view-and-draw-chess-board)

**Comment by Phatkid98** [comment]
Hey Justin, 
Is there already a "name" column in someone else's schema? Other than that on conflict that's showing, it looks good

**Comment by jwmunn** [comment]
I was waiting for that to happen. Everything should be resolved and ready to merge now.

**Comment by kboygit** [comment]
hey good job guys! 
screen shot 2017-05-26 at 11 23 33 pm
screen shot 2017-05-26 at 11 23 21 pm
screen shot 2017-05-26 at 11 23 39 pm

**Comment by ilyakrasnov** [comment]
👍

**Pull request merged**
