### PR TITLE
fixed unnecessary association

### PR DESCRIPTION
**Pull request by kirbygit**
- removed has_many :pieces since pieces is associated with games

### CODE REVIEW

**Comment by kirbygit** [comment]
- this is a change to pr #26 inline to associations

**Comment by fistoriza** [comment]
👍

**Comment by kirbygit** [comment]
@fistoriza yea however it didnt cause a big problem since we dont have too much functionality added yet

**Comment by fistoriza** [comment]
👍

**Comment by kirbygit** [comment]
@fistoriza you can merge this

**Pull request merged**
