### PR TITLE
Select and move piece

### PR DESCRIPTION
**Pull request by jwmunn**
- Selecting a square containing a piece adds `.active` class
- If you re-click selected piece it removes `.active` class
- If a piece is already selected and another square is clicked it moves the piece to that square

---

To test go to game#show view.
Create pieces in the console:
```console
game = Game.last
```
Create pieces with the same `game_id`
```console
game.pieces << Piece.create(name: ‘Knight’, x_pos: 1, y_pos: 2, game_id: 2)
```
Then you should be able to click and move pieces.

### CODE REVIEW

**Comment by jwmunn** [comment]
[Ability to select and move piece](https://trello.com/c/zwkyLmMl/19-ability-to-select-and-move-piece)

**Comment by ilyakrasnov** [comment]
Looks 👍. As @jwmunn posted, the card suggests to first do it without ajax.. Kudos on going the extra mile 😄

**Comment by ilyakrasnov** [comment]
Let's merge it! 😉

**Comment by fistoriza** [comment]
🥇

**Pull request merged**
