### PR TITLE
Integrated bootstrap and devise

### PR DESCRIPTION
**Pull request by jwmunn**
- Added Bootstrap
- Added Devise
- Put general devise links in top nav
- Used Bootstrap to style devise forms and flash alerts

### CODE REVIEW

**Comment by kboygit** [comment]
✨✨✨👌  Looking good just a small commit to refresh the ci and tweak for minor style format✨✨✨

**Comment by kboygit** [comment]
✨✨✨👌 good job just need to make another pr to minimize commits ✨✨✨

**Comment by ilyakrasnov** [comment]
👍

**Comment by kboygit** [comment]
- resolved conflicts

**Pull request merged**
