### PR TITLE
Piece Model and Migration / Travis CI fixes

### PR DESCRIPTION
**Pull request by nnadkarny**
- Generated the Piece model and migration
- Added tables to the migration based on specs in database spreadsheet
- Ran migration, updating schema.rb with new tables
- Auto-generated Factory and Rspec files for Piece model

- Added fixes to Travis CI files to fix test database errors

### CODE REVIEW

**Comment by kboygit** [comment]
Good job man , just make a new pr that finalize all everything youve done into just one whole commit with the description of the pull request

**Comment by kboygit** [comment]
[Build the Models for the Database (Part II) [ Blocker for next week ]](https://trello.com/c/arROHsQB/8-build-the-models-for-the-database-part-ii-blocker-for-next-week)

**Comment by ilyakrasnov** [comment]
👍

**Comment by kboygit** [comment]
good to go

**Pull request merged**
